bot/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'Accounts'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('new_account', views.new_account, name = 'new_account'),
	path('new_account_token', views.new_account_token, name = 'new_account_token'),
	path('new_acc_login_or_token', views.new_acc_login_or_token, name='new_acc_login_or_token'),
	path('new', views.new, name='new'),
	path('new_group', views.new_group, name='new_group'),
	path('<int:account_id>/', views.settings, name = 'settings'),
	path('<int:account_id>/save', views.save, name = 'save'),
	path('create_account', views.create_account, name = 'create_account'),
	path('create_account_token', views.create_account_token, name = 'create_account_token'),
	path('create_group', views.create_group, name='create_group'),
	path('start', views.start, name='start'),
	path('end', views.end, name='end'),
	path('<int:account_id>/delete_yesno', views.delete_yesno, name='delete_yesno'),
	path('<int:account_id>/delete_account', views.delete_account, name='delete_account'),
]

bot/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('accounts.urls')),
    url(r'^favicon\.ico$',RedirectView.as_view(url='/images/favicon.ico')),
]

bot/apps/accounts/models.py
from django.db import models


class Account(models.Model):
	call = models.CharField('Имя бота', max_length=30)
	token = models.CharField('Токен бота', max_length=100)
	name = models.CharField('Обращение бота', max_length=15, default='Бот')
	sleep = models.PositiveIntegerField('Задержка перед отправкой сообщения', default=0)
	voice_bot = models.BooleanField('Ответ голосовыми сообщениями', default=False)
	status = models.TextField('Статус', default='vk.com/roofchick')
	mark = models.CharField('Метка бота', max_length=15, default='bot')
	auto_friends = models.BooleanField('Автоматическое добавление в друзья', default=True)
	ls_user = models.BooleanField('Обращение в личных сообщениях', default=True)
	group_name = models.BooleanField('Обращение к пользователю в беседах', default=False)
	base_name = models.CharField('База ответов', max_length=15, default='base.bin')
	group = models.PositiveIntegerField('id сообщества, у пользователей = 0', default=0)
	commands = models.TextField('Команды (не работает)', default='.')
	reply = models.BooleanField('Пересылать сообщения собеседника в беседах', default=True)
	

class Status(models.Model):
	
	name = models.TextField('Э', default='Ы')
	
	work = models.BooleanField('Статус работы аккаунтов', default=False)
	
	
	def __str__(self):
		return self.name

bot/apps/accounts/views.py
from django.shortcuts import render

from django.http import Http404, HttpResponseRedirect

from django.urls import reverse

from .models import Account, Status

import requests

from func.account_start import start_bot

a = Status.objects.all()[0]
if a.work:
	start_bot()

def index(request):
	a = Status.objects.all()[0]
	accounts_list = Account.objects.all()
	return render(request, 'accounts/list.html', {'accounts_list': accounts_list, 'start': a.work})

def settings(request, account_id):
	try:
		a = Account.objects.get( id = account_id )
	except:
		raise Http404('Аккаунт не найден')

	return render(request, 'accounts/settings.html', {'account': a})


def save(request, account_id):
	try:
		a = Account.objects.get( id = account_id )
	except:
		raise Http404('Аккаунт не найден')
		
	try:
		a.name = request.POST['name']
	except:
		pass

	try:
		a.mark = request.POST['mark']
	except:
		pass
	
	try:
		a.sleep = request.POST['sleep']
	except:
		pass

	try:
		a.status = request.POST['status']
	except:
		pass
	
	try:
		x = request.POST['auto_friends']
		a.auto_friends = True
	except:
		a.auto_friends = False
	
	try:
		x = request.POST['ls_user']
		a.ls_user = True
	except:
		a.ls_user = False
	
	try:
		x = request.POST['group_name']
		a.group_name = True
	except:
		a.group_name = False
	
	try:
		x = request.POST['voice_bot']
		a.voice_bot = True
	except:
		a.voice_bot = False
	
	try:
		x = request.POST['reply']
		a.reply = True
	except:
		a.reply = False
		
		

	a.save()

	base_name = request.POST['base_name']
	try:
		with open(f"base/{base_name}") as f:
			pass
		a.base_name = base_name
		a.save()
		return HttpResponseRedirect( reverse('Accounts:settings', args=(a.id,)) )
	except:
		print(base_name)
		return render(request, 'accounts/settings.html', {'account': a, 'error_base': base_name})
	

def new_account(request):
	return render(request, 'accounts/new_account.html')

def new_account_token(request):
	return render(request, 'accounts/new_account_token.html')

def new(request):
	return render(request, 'accounts/new.html')

def new_acc_login_or_token(request):
	return render(request, 'accounts/new_acc_login_or_token.html')
	
def create_group(request):
	
	token = request.POST['longpoll_token']
	
	id = request.POST['id']
	
	a = requests.get('https://api.vk.com/method/groups.getLongPollServer', params={'lp_version': 3, 'v': 5.121 , 'access_token': token, 'group_id': id})
	
	try:
		ts = a.json()['response']['ts']
	except:
		return render(request, 'accounts/new_account.html', {'error': True})
		
	a = requests.get('https://api.vk.com/method/groups.getById', params={'access_token': token, 'group_id': id, 'v': 5.121})
	
	name = a.json()['response'][0]['name']
		
	a = Account(call=name, token=token, group=id)
	
	a.save()
	
	return render(request, 'accounts/settings.html', {'account': a})
	
def new_group(request):
	return render(request, 'accounts/new_group.html')

def create_account(request):
	
	login = request.POST['login']
	password = request.POST['password']
	
	a = requests.get(f'https://api.vk.com/oauth/token?grant_type=password&client_id=2274003&client_secret=hHbZxrka2uZ6jB1inYsH&username={login}&password={password}')
	try:
		token = a.json()['access_token']
	except:
		print(a.text)
		return render(request, 'accounts/new_account.html', {'error': True})
	
	a = requests.get('https://api.vk.com/method/account.getProfileInfo', params={'v': 5.121, 'access_token': token})
	
	name = a.json()['response']['first_name']
	last_name = a.json()['response']['last_name']
		
	a = Account(call=f'{name} {last_name}', token=token)
	
	a.save()
	
	return render(request, 'accounts/settings.html', {'account': a})


def start(request):
	
	a = Status.objects.all()[0]

	accounts_list = Account.objects.all()

	if accounts_list:
		
		a.work = True
		a.save()
		
		start_bot()
	
		return render(request, 'accounts/list.html', {'accounts_list': accounts_list, 'start': a.work})

	else:
		return render(request, 'accounts/list.html', {'accounts_list': accounts_list, 'start': a.work})
	
	
def end(request):
	
	a = Status.objects.all()[0]
	a.work = False
	a.save()
	
	accounts_list = Account.objects.all()
	
	return render(request, 'accounts/list.html', {'accounts_list': accounts_list, 'start': a.work})
	
def delete_yesno(request, account_id):
	return render(request, 'accounts/delete_yesno.html', {'account_id': account_id})
	
def delete_account(request, account_id):
	Account.objects.get(id=account_id).delete()
	return index(request)

def create_account_token(request):
	
	token = request.POST['token']
	
	a = requests.get('https://api.vk.com/method/account.getProfileInfo', params={'v': 5.121, 'access_token': token})

	try:
		name = a.json()['response']['first_name']
		last_name = a.json()['response']['last_name']
	except:
		return render(request, 'accounts/new_account_token.html', {'error': True})
	
	a = requests.get('https://api.vk.com/method/account.getProfileInfo', params={'v': 5.121, 'access_token': token})
		
	a = Account(call=f'{name} {last_name}', token=token)
	
	a.save()
	
	return render(request, 'accounts/settings.html', {'account': a})

bot/templates/accounts/delete_yesno.html
{% extends 'base.html' %}

{% block title %}Подтвердите удаление аккаунта{% endblock %}

{% block content %}
	<div class="AccountDiv AccountName">
	<div class="auth_name">

	<h2>Вы уверены, что хотете удалить аккаунт?</h2>
	</div></div>


	<table class="DeleteYesNo">
	<tr><th>
		<form action="{% url 'Accounts:settings' account_id %}", method='POST'>
		 
			{% csrf_token %}
			
			<div class="AccountDiv NoDelete"><button type="submit" class="AccountSettings"><h3 class="Start">Нет</h3></button></div><br/><br/>
	
		</form>
	</th>

	<th>
	<form action="{% url 'Accounts:delete_account' account_id %}", method='POST'>
	 
		{% csrf_token %}
		<div class="AccountDiv YesDelete"><button type="submit" class="DeleteAccount"><h3 class="Delete">Да</h3></button></div><br/><br/>

	</form>
	</th></tr></table>

{% endblock %}

bot/templates/accounts/list.html
{% extends 'base.html' %}
{% block title %}Список аккаунтов{% endblock %}
{% block content %}
{% if start %}
	<form action="/accounts/end", method='POST'>
		{% csrf_token %}
		<div class="Start"><button type="submit" class="StartBot"><h3 class="Start">Выключить бота</h3></button></div>
	</form>
{% else %}
	{% if accounts_list %}
		{% for a in accounts_list %}
		<form action="{% url 'Accounts:settings' a.id %}", method='POST'>
			{% csrf_token %}
			<div class="AccountDiv"><button type="submit" class="AccountSettings">
			<div class="AccountName">
				<h2>{{a.call}}</h2>
				<p>Обращение: {{a.name}}; Метка: ({{a.mark}})</p>
			</div></button></div></form><br/>{% endfor %}
	<form action="/accounts/start", method='POST'>{% csrf_token %}
		<div class="Start"><button type="submit" class="StartBot"><h3 class="Start">Запустить бота</h3></button></div><br/><br/>
	</form>
	{% endif %}
	<form action="{% url 'Accounts:new' %}", method='POST'>{% csrf_token %}
		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Добавить новую страницу/группу</h3></button></div>
	</form>
{% endif %}
{% endblock %}

bot/templates/accounts/new.html
{% extends 'base.html' %}

{% block title %}Новый аккаунт{% endblock %}

{% block content %}

	<form action="{% url 'Accounts:index' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Назад</h3></button></div><br/><br/>

	</form>



	<form action="{% url 'Accounts:new_acc_login_or_token' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Подключить бота к странице</h3></button></div><br/>

	</form>



	<form action="{% url 'Accounts:new_group' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Подключить бота к группе</h3></button></div>

	</form>

</table>

{% endblock %}

bot/templates/accounts/new_acc_login_or_token.html
{% extends 'base.html' %}

{% block title %}Новый аккаунт{% endblock %}

{% block content %}

	<form action="{% url 'Accounts:new' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Назад</h3></button></div><br/><br/>

	</form>



	<form action="{% url 'Accounts:new_account' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Войти через логин или пароль</h3></button></div><br/>

	</form>



	<form action="{% url 'Accounts:new_account_token' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Войти через токен</h3></button></div>

	</form>

</table>

{% endblock %}

bot/templates/accounts/new_account.html
{% extends 'base.html' %}
{% block title %}Новый аккаунт{% endblock %}
{% block content %}
	<form action="{% url 'Accounts:new_acc_login_or_token' %}", method='POST'>
		{% csrf_token %}
		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Назад</h3></button></div><br/><br/>
	</form>
	<div class="AccountDiv AccountName">
	<div class="auth_name">
		<h2>Подключение бота к странице</h2>
		<h4>(Введите логин и пароль от нужного аккаунта ВКонтакте)</h4>
	</div></div><br/>
	<div class="AccountDiv AccountName"><div class="auth">
		<form action="/accounts/create_account", method='POST'>
			{% csrf_token %}
			<p>Логин</p>
			<input type='text' name="login" required=""></input><br>
			<p>Пароль</p>
			<input type='password' name="password" required=""></input><br><br>
			{% if error %}
	    <div id="error" title="Error"><p>Неправильный логин или пароль</p></div>
			{% endif %}
			<button type="submit" class="Save">Войти</button>
		</form></div></div>
{% endblock %}

bot/templates/accounts/new_account_token.html
{% extends 'base.html' %}

{% block title %}Новый аккаунт{% endblock %}

{% block content %}

	<form action="{% url 'Accounts:new_acc_login_or_token' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Назад</h3></button></div><br/><br/>

	</form>

	<div class="AccountDiv AccountName">
	<div class="auth_name">
		<h2>Подключение бота к странице</h2>
		<h4>Получить токен можно на сайте vkhost.github.io</h4>
		<h4>Рекомендуется токен от Kate Mobile</h4>
	</div></div><br/>

	<div class="AccountDiv AccountName">
	<div class="auth">

		<form action="/accounts/create_account_token", method='POST'>

			{% csrf_token %}
			
			<p>Токен</p>
			<input type='text' name="token" required=""></input><br/><br>
			
			{% if error %}
	    <div id="error" title="Error">
	        <p>Неправильный токен</p>
	    </div>
			{% endif %}

			<button type="submit" class="Save">Войти</button>

		</form>
	</div>
	</div>



{% endblock %}

bot/templates/accounts/new_group.html
{% extends 'base.html' %}

{% block title %}Новый аккаунт{% endblock %}

{% block content %}

	<form action="{% url 'Accounts:new' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Назад</h3></button></div><br/><br/>

	</form>

	<div class="AccountDiv AccountName">
	<div class="auth_name">
		<h2>Подключение бота к группе</h2>
		<h4>Обязательно прочитайте инструкцию внизу этой страницы</h4>
	</div></div><br/>

	<div class="AccountDiv AccountName">
	<div class="auth">

	<form action="/accounts/create_group", method='POST'>

		{% csrf_token %}
		
		<p>Ключ доступа</p>
		<input type='text' name="longpoll_token" required=""></input><br><br>
		
		<p>id сообщества</p>
		<input type='text' name="id" required=""></input><br><br>
		
		{% if error %}
    <div id="error" title="Error">
        <p>Неправильный логин или пароль</p>
    </div>
		{% endif %}

		<button type="submit" class="Save">Войти</button>

	</form></div>
	</div><br><br>

	<div class="AccountDiv AccountName">
	<div class="auth_name">

	<h2>Инструкция</h2>
	<h4>Обязательно выполните эти действия:</h4>
	<h4>(Все действия делать через компьютер или версию сайта для ПК с телефона)</h4>

	<div class="Instr">
	<ul>
		<li>Открыть вкладку &laquo;Управление&raquo; на странице сообщества</li>
		<li>Во вкладке &laquo;Сообщения&raquo;:</li>
		<ol><li>Включить сообщения сообщества и нажать на кнопку &laquo;Сохранить&raquo;</li></ol>
		<li>Во вкладке &laquo;Настройки для бота&raquo;</li>
		<ol>
			<li>Включить возможности ботов</li>
			<li>Включить пункт &laquo;Разрешать добавлять сообщество в беседы&raquo;</li>
			<li>нажать на кнопку &laquo;Сохранить&raquo;</li>
		</ol>
		<li>Перейти в раздел &laquo;Настройки&raquo;</li>
		<li>Перейти в подраздел &laquo;Работа с API&raquo;</li>
		<li>Перейти на вкладку &laquo;Long Poll API&raquo;</li>
		<li>На вкладке &laquo;Настройки&raquo;:</li>
		<ol>
			<li>Включить Long Poll API</li>
			<li>Выбрать версию API 5.120 или новее</li>
		</ol>
		<li>На вкладке &laquo;Типы событий&raquo;:</li>
		<ol>
			<li>Включить &laquo;Входящее сообщение&raquo;</li>
		</ol>
		<li>Перейти на вкладку &laquo;Ключи доступа&raquo;:</li>
		<ol>
			<li>Нажать на кнопку&laquo;Создать ключ&raquo;</li>
			<li>Разрешить доступ ко всем пунктам</li>
			<li>Нажать на кнопку &laquo;Создать&raquo;</li>
			<li>Подтвердить номер телефона</li>
			<li>Скопировать ключ доступа и вставить в поле &laquo;Ключ доступа&raquo; вверху этой страницы</li>
		</ol>
		<li>Теперь получаем id сообщества:</li>
		<ol>
			<li>Вернуться на страницу сообщества</li>
			<li>Скопировать ссылку на сообщество</li>
			<li>Перейти на сайт <a href="https://regvk.com/id/">REGVK</a></li>
			<li>Вставить ссылку на сообщество и нажать на кнопку &laquo;Определить ID&raquo;</li>
			<li>Скопировать id сообщества из пункта &laquo;ID публичной страницы&raquo;</li>
			<li>Вставить id в поле &laquo;id сообщества&raquo; вверху этой страницы</li>
		</ol>
		<li>Нажать кнопку &laquo;Войти&raquo; вверху этой страницы</li>
	</ul>

</div></div></div>






{% endblock %}

bot/templates/accounts/settings.html
{% extends 'base.html' %}
{% block title %}{{account.call}}{% endblock %}
{% block content %}


	<form action="{% url 'Accounts:index' %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="AccountSettings"><h3 class="Start">Вернуться к списку аккаунтов</h3></button></div><br/><br/>

	</form>

	<div class="AccountDiv AccountName">
	<div class="auth_name">
	<h2>Аккаунт: {{account.call}}</h2>
	</div></div><br/>


	<div class="AccountDiv AccountName">
	<div class="auth">

	<form action="{% url 'Accounts:save' account.id %}", method='POST'>
		{% csrf_token %}
		<p>Обращение к боту</p>
		<input name="name" value="{{account.name}}"></input><br>
		<p>Метка бота (Отображается в скобках в начале сообщений)</p>
		<input name="mark" value="{{account.mark}}"></input><br>
		<p>Задержка перед отправкой сообщений</p>
		<input name="sleep" value="{{account.sleep}}" type="number"></input><br>
		<p>База ответов</p>
		<input name="base_name" value="{% if error_base %}{{error_base}}{% else %}{{account.base_name}}{% endif %}", id="base_name" /><br/>
		{% if error_base %}
			<p style="color:Red;">База ответов не найдена</p>
		{% endif %}
		{% if not account.group %}
			<p>Статус</p>
			<textarea name="status" cols="40" rows="4">{{account.status}}</textarea><br><br>
			<input name="auto_friends" value="{{account.auto_friends}}" type="checkbox" id="auto_friends"
			{% if account.auto_friends %}
			 checked
			{% endif %}
			/><label for="auto_friends">Принимать заявки в друзья</label><br><br>
		{% else %}
			<br/>
		{% endif %}
		<input name="ls_user" value="{{account.ls_user}}" type="checkbox" id="ls_user"
		{% if account.ls_user %}
		 checked
		{% endif %}
		/><label for="ls_user">Обращение в личных сообщениях</label><br><br>
		<input name="group_name" value="{{account.group_name}}" type="checkbox" id="group_name"
		{% if account.group_name %}
		 checked
		{% endif %}
		/><label for="group_name">Обращение к пользователю в беседах (Бот будет отвечать "Имя, сообщение")</label><br><br>
		<input name="voice_bot" value="{{account.voice_bot}}" type="checkbox" id="voice_bot"
		{% if account.voice_bot %}
		 checked
		{% endif %}
		/><label for="voice_bot">Ответ голосовыми сообщениями</label><br><br>
		<input name="reply" value="{{account.reply}}" type="checkbox" id="reply"
		{% if account.reply %}
		 checked
		{% endif %}
		/><label for="reply">Пересылать сообщения собеседников в беседах</label><br><br>
		<button type="submit" class="Save">Сохранить</button>
	</form>

	</div>
	</div><br><br>


	<form action="{% url 'Accounts:delete_yesno' account.id %}", method='POST'>

		{% csrf_token %}

		<div class="AccountDiv"><button type="submit" class="DeleteAccount"><h3 class="Delete">Удалить аккаунт</h3></button></div><br/><br/>

	</form>

{% endblock %}

bot/templates/base.html
<!DOCTYPE html>
	 <head>
		 <title>{% block title %}Аккаунт{% endblock %}</title>
		 <meta charset="UTF-8">
		 <style>
		 	body {
		 		margin: 0;
				background-color: #d0f0c0;#e2f7df;
			}

			header {
				width: 100%;
				background: #67e667;
				height: 75px;
				overflow: hidden;
			}

			h1.BotNameHeader {
				text-align: center;
				color: #003300;
				padding: 0px 0px 15px 0px;
				border-bottom: 2px solid #003300;
			}
			div.content {
				padding: 1% 0%;
			}
			button.StartBot {
				border-radius: 17px;
				height: 55px;
				width: 170px;
				background: #67e667;
				border: 1.5px solid #003300;		
			}
			button.AccountSettings {
				border-radius: 17px;
				background: #67e667;
				border: 1.5px solid #003300;
				padding: 0.5em 1em 0.5em 1em;
				align-items: left;
			}
			button.Save {
				border-radius: 17px;
				background: #259925;
				border: 1.5px solid #003300;
				padding: 0.5em 1em 0.5em 1em;
				align-items: left;
			}
			input, textarea {
				border-radius: 10px;
				background: #32cd32;
				border: 1.5px solid #003300;
				padding: 0.5em 1em 0.5em 1em;
				align-items: left;
			}
			h3.Start {
				color: #003300;
			}
			div.AccountName {
				color: #003300;
			}
			div, h3, h2 {
				color: #003300;
			}
			div.Start {
				text-align: center;
			}
			div.AccountDiv {
				text-align: center;
			}
			th.AccountNewDiv {
				text-align: right;
				width: 50%;
			}
			table.TableNew {
				width: 100%;
			}
			div.auth {
				border-radius: 17px;
				background: #67e667;
				border: 1.5px solid #003300;
				padding: 1em 3em 2em 3em;
				align-items: left;
				display: inline-block;
				text-align: center;
			}
			div.auth_name {
				border-radius: 17px;
				background: #67e667;
				border: 1.5px solid #003300;
				padding: 0.5em 1em 0.5em 1em;
				align-items: left;
				display: inline-block;
				text-align: center;
			}
			button.DeleteAccount {
				border-radius: 17px;
				background: #ffa8af;
				border: 3px solid #ff0000;
				padding: 0.5em 1em 0.5em 1em;
				align-items: left;
			}
			h3.Delete {
				color: #ff0000;
			}
			div.Instr {
				text-align: left;
			}
			table.DeleteYesNo {
				width: 100%;
			}

		 </style>



	 </head>
	 <body>
		<header>
	 		<h1 class="BotNameHeader">VKBot Django</h1>
	 	</header>

	 	<div class="content" width=50%>
	 		{% block content %}Произошла ошибка, обновите страницу или обратитесь к https://vk.com/roofchick{% endblock %}
		</div>

	 </body>
 </html>